name: hare`s blog

on: [push]

env:
  USER: hare001
  EMAIL: jiahan001@gmail.com
  GH_REF: github.com/hare001/hare001.github.io.git
  THEME_REF: github.com/hare001/mogege.git
  THEME_NAME: mogege
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # 这里的 token 需要自己在 GitHub settings 中部署，并利用 actions 的 secrets 功能

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # 使用预编译的 Hugo 二进制文件
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: "latest"
          # 使用 Hugo-extended 版本
          extended: true

      # 新建站点
      - name: new site
        run: |
          hugo new site $HOME/blog

      # 获取主题
      - name: get theme
        run: |
          git clone --depth=1 "https://$THEME_REF" $HOME/blog/themes/$THEME_NAME

      # 获取 username.github.io 以保持 commit 记录
      - name: get username.github.io
        run: |
          git clone --no-checkout "https://$GH_REF" $HOME/blog/public

      # 获取内容文件
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      # 将内容文件复制进入站点内
      - name: copy in
        run: |
          rm -rf $HOME/blog/config.toml $HOME/blog/content/
          /bin/cp -rf config.toml $HOME/blog/config.toml
          /bin/cp -rf content/ $HOME/blog/content/
          /bin/cp -rf static/* $HOME/blog/public/
          /bin/cp -rf layouts/* $HOME/blog/layouts/

      # build
      - name: build
        run: |
          cd $HOME/blog
          HUGO_ENV=production hugo --gc --minify

      # 将生成出的站点推向 username.github.io
      - name: publish
        run: |
          cd $HOME/blog/public
          git config --global user.name $USER
          git config --global user.email $EMAIL
          git add .
          git commit -m "Auto Update by Workflow: `date +'%Y-%m-%d %H:%M:%S'`"
          git push "https://$USER:$GH_TOKEN@$GH_REF" master:master
